name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (patch, minor, major, or specific version like 1.2.3)'
        required: false
        default: 'patch'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Run tests
        run: npm test
        
      - name: Build package
        run: npm run build
        
      - name: Update version (if specified)
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
        
      - name: Verify package contents
        run: |
          echo "📦 Package contents:"
          npm pack --dry-run
          echo "📋 Files that will be published:"
          npm publish --dry-run
          
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub release (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version || 'auto' }}
          name: Release v${{ github.event.inputs.version || 'auto' }}
          body: |
            ## Changes
            
            Automated release for version ${{ github.event.inputs.version || 'current' }}
            
            ### Package Info
            - Built and tested ✅
            - Published to NPM ✅
            
            ### Installation
            ```bash
            npm install vite-plugin-sveltekit-decorators
            ```
          draft: false
          prerelease: false
